// Generated by Wrangler by running `wrangler types`

interface Env {
	SESSION_KV: KVNamespace;
	MODE: "production" | "develop" | "staging";
	BASE_URL: "https://react-router-cloudflare-workers-template.az-tech-manage.workers.dev" | "http://localhost:5173";
	CLIENT_SECRET: string;
	CLIENT_ID: string;
	SESSION_SECRET: string;
	DB: D1Database;
}
